### ISSUE TITLE
config.json options for influxdb collector seem broken

### ISSUE THREAD

**Issue by na--** [k6io/k6#1519]
As [reported in the community forum](https://community.k6.io/t/influxdb-tagsasfields-configuration-issues/721), this no longer seems to work: https://github.com/loadimpact/k6/blob/master/samples/config.json#L5

We need to see if this applies to other options or collectors as well... The cloud collector seems to work, since the token saved by `k6 login cloud` works, but we need to investigate if other things are broken as well.

**Comment by na--** [comment]
This might have been fixed by https://github.com/k6io/k6/pull/1953

**Comment by MStoykov** [comment]
This seems to have been fixed in v0.31.0 as I can reproduce it with v0.30.0 but not v0.31.1 (but .1 had nothing to do with it) so it's fixed :tada:
