### ISSUE TITLE
Prometheus metrics endpoint in k6 REST API

### ISSUE THREAD

**Issue by szkiba** [k6io/k6#1787]
I'm going to use smoke test with a long running k6 instance for monitoring my service. I'd like to collect metrics from test using Prometheus.

This is not about exporting, pushing k6 normal result to Prometheus, that is another story. This is about monitoring smoke test process itself and make alerts on some monitored metric values.

I'd like to develop this feature if you agree on that this is useful, and there is a chance to merge.

## Feature Description
k6 REST API endpoint for monitoring test process with Prometheus. Primary use case is a long running smoke test with monitored metrics. Collect metrics and make alerts when something isn't works as expected.

## Suggested Solution
Add "/v1/monitor" REST API endpoint, to provide Prometheus formatted metrics. Add same metrics as  the "/v1/metrics" endpoint. Use https://godoc.org/github.com/prometheus/common/expfmt for formating metrics in Prometheus format.

**Comment by alexanderscott** [comment]
+1

**Comment by benc-uk** [comment]
I've created a project to explore providing a sidecar solution to getting data from k6 into Prometheus

https://github.com/benc-uk/k6-prometheus-exporter

**Comment by na--** [comment]
Worth mentioning that this will have to be done as an output, for the reasons explained in https://github.com/loadimpact/k6/issues/1875#issuecomment-788890152
The good news is that k6 will support output extensions after k6 v0.31.0 (slated to be released next week), so if anyone is interested, an extension with this should be easy to create soon.

**Comment by na--** [comment]
Worth repeating https://github.com/k6io/k6/pull/1792#issuecomment-834608942 here as well, if anyone stumbles on this issue: @szkiba has created an [xk6](https://github.com/k6io/xk6) output extension for Prometheus: https://github.com/szkiba/xk6-prometheus

**Comment by szkiba** [comment]
> Worth repeating [#1792 (comment)](https://github.com/k6io/k6/pull/1792#issuecomment-834608942) here as well, if anyone stumbles on this issue: @szkiba has created an [xk6](https://github.com/k6io/xk6) output extension for Prometheus: https://github.com/szkiba/xk6-prometheus

Yes, and this is why I close this PR now...
