### ISSUE TITLE
Add newrelic as an output option

### ISSUE THREAD

**Issue by simskij** [k6io/k6#1801]
Currently, only the `datadog` collector supporting sending tags. However,  other popular implementations support sending and receiving tags as well:

- https://github.com/atlassian/gostatsd
- https://github.com/newrelic/nri-statsd.

## Feature Description

I want to be able to send statsd metrics **with** tags to `nri-statsd` **without** having to use `--out datadog` as the result output. Running k6 with the `--out datadog`, but pointing it at `nri-statsd` works, although looking awkward and not being that intuitive.

## Suggested Solution (optional)

- Create another alias so that `--out datadog` and `--out newrelic` may both be used for the existing implementation
- Add `--out newrelic` as a separate option
- Add a parameter that enables the sending of tags in `--out statsd`

**Comment by na--** [comment]
I'd prefer the last suggested option. I don't know the details of the data format and its various implementations, but maybe something like a `version` option to the current statsd collector, with `v1` being the default current implementation and `v2` being usable for datadog, newrelic and any other similar services.

Alternatively, if statsd v2 is not really a standard, or if there are some differences between the proprietary implementations of NewRelic and DataDog, maybe we can have a `variant` option instead, with the possible values of `original`, `newrelic`, and `datadog`? :man_shrugging: 

Outputs are currently fairly painful to add in k6 and we hope to fix that (and enable output [xk6](https://github.com/k6io/xk6) extensions) in k6 v0.31.0, so ~March. That should unlock a lot of flexibility and it might make sense to add separate outputs then. Though, to me, it's more likely that we'd like to merge the current `datadog` output, which already [shares most of its code](https://github.com/loadimpact/k6/blob/c00a85bfea21d748f0f9d11fdbc326087f34c411/stats/datadog/collector.go#L31) with the `statsd` one, e.g. make it an alias to `statsd{version=v2}` or whatever.

That said, I am not familiar with the ecosystem, so I may be very wrong. For example, if some proprietary statsd-based service has some significant feature not available in others, it might make sense to have a separate output for it... :man_shrugging:
