### ISSUE TITLE
Moving the repo to github.com/k6io

### ISSUE THREAD

**Issue by na--** [k6io/k6#1921]
As we mentioned in the [k6 v0.31.0 release notes](https://github.com/loadimpact/k6/blob/master/release%20notes/v0.31.0.md#planned-future-breaking-changes), we're going to move the k6 repo to the [k6io GitHub organization](https://github.com/k6io) as a part of the re-branding of Load Impact to k6. We've already moved all of the other repos, k6 is the last one, and its move will probably happen some time this week.

The actual move will happen in 2 steps:
- moving the repo from the GitHub UI - this should be transparent and without issues, since GitHub automatically redirects all links from the old repo address to the new one
- ~changing the Go package names from `github.com/loadimpact/k6/...` to `github.com/k6io/k6/...`~ update, see https://github.com/k6io/k6/issues/1921#issuecomment-811072303, we decided to go with vanity URLs like `go.k6.io/k6/...`  - this will likely break all Go apps that depend on k6 as a library when they update their used k6 versions. This includes currently open PRs and https://github.com/k6io/xk6, for which we'll release a new version that only works with new corresponding new k6 versions. Because of go modules and the github redirects, old k6 versions should still continue to work fine with the old module paths.

**Comment by na--** [comment]
The repo was moved to https://github.com/k6io/k6, we plan to rename the Go module paths to match next week, which would probably break a lot of things.

**Comment by na--** [comment]
We decided that instead of migrating the Go module paths to `github.com/k6io/k6/...`, we'll use vanity URLs, so move to something like `go.k6.io/k6/...`. We plan to do that towards the end of April-start of May, before the k6 v0.32.0 release.

**Comment by na--** [comment]
We should remember to update these 2 lines when we change the package paths:
https://github.com/k6io/k6/blob/5dc1187d4bd77085e29d9faf605ff2a958ee4f7f/.github/workflows/all.yml#L113
https://github.com/k6io/k6/blob/5dc1187d4bd77085e29d9faf605ff2a958ee4f7f/build-release.sh#L22

And also, I noticed that the [homebrew k6 package doesn't set `VersionDetails`](https://github.com/Homebrew/homebrew-core/blob/06d530139344bfae423c02bf423c9dc85ce0de4d/Formula/k6.rb#L18), so we should probably make a PR to fix that after we rename the paths.

**Comment by na--** [comment]
I'll close this, since the repo module paths now use `go.k6.io` :tada:

**Comment by jlmorton** [comment]
Hi, I believe the changes in this issue may have broken `go get`.

   $ go get go.k6.io/k6@v0.31.1                                                      
   go get: go.k6.io/k6@v0.27.1 updating to
   	go.k6.io/k6@v0.31.1: parsing go.mod:
   	module declares its path as: github.com/loadimpact/k6
   	        but was required as: go.k6.io/k6

Alternatively,

   $ go get github.com/k6io/k6@v0.31.1                                              
   go get: github.com/k6io/k6@v0.27.1 updating to
	   github.com/k6io/k6@v0.31.1: parsing go.mod:
   	   module declares its path as: github.com/loadimpact/k6
   	           but was required as: github.com/k6io/k6

**Comment by MStoykov** [comment]
hi @jlmorton, 

While the repo is renamed we are releasing a new version today (hopefully :crossed_fingers: ) at which point `go get go.k6.io/k6` will start working, until then it tries to pull the latest version/tag it can find. Which is `v0.31.1` and it is *not* with the renamed path.

If you really want to start using the new path you can do `go get go.k6.io/k6@master` which will not a pull a tagged version but the latest master which *is* actually named correctly. Or you can continue to use the `github.com/loadimpact/k6` until we release a version, again *hopefully* today.

**Comment by MaximeTriguero** [comment]
``` bash
$ go install github.com/go.k6.io/k6/cmd/xk6@latest
go install github.com/go.k6.io/k6/cmd/xk6@latest: module github.com/go.k6.io/k6/cmd/xk6: git ls-remote -q origin in C:\Users\Maxime\go\pkg\mod\cache\vcs\6bd808e12cf43f2b8116f7a0ef480b65b34c32d9457aa877de4ead31d0c55d60: exit status 128:
        remote: Repository not found.
        fatal: repository 'https://github.com/go.k6.io/k6/' not found
```
```bash 
$ go install github.com/k6io/xk6/cmd/xk6@latest
go install github.com/k6io/xk6/cmd/xk6@latest: github.com/k6io/xk6@none updating to
        github.com/k6io/xk6@v0.4.5: parsing go.mod:
        module declares its path as: go.k6.io/xk6
                but was required as: github.com/k6io/xk6

```
How can I get xk6 install please :)

**Comment by MStoykov** [comment]
@MaximeTriguero as per the update documentation `go install go.k6.io/xk6/cmd/xk6@latest`, without any `github.com/` infront
