### ISSUE TITLE
Not able to set authorisation token in headers

### ISSUE THREAD

**Issue by baninaveen** [k6io/k6#1927]
We are not able to set the basic auth token in the headers in GET method

const params = {
    headers: {
        "Authorization": `Basic ${encodedCredentials}`,
    }
  };

let res = http.get(`${BASE_URL}`, params);

**Comment by imiric** [comment]
Hi, please post support questions on [the community forum](https://community.k6.io/).

Try using `run --http-debug` to see what k6 is actually sending, but you seem to be setting the header correctly, so it could be an issue with your service or just wrong credentials.

**Comment by baninaveen** [comment]
it does not added. So I started add auth with url http://USERNAME:PASSWORD@BASE_URL
AND it worked
