### ISSUE TITLE
Support command line parameters for bandwidth limitation

### ISSUE THREAD

**Issue by gbabyX** [k6io/k6#1969]
Add a  parameter in the “run” command for bandwidth limitation.

## Feature Description
The metric of data_send we can see the data sending speed, I hope to have a parameter to set its value when running the run command.

**Comment by na--** [comment]
Thanks for making this issue, though I think it is a subset of the features described in https://github.com/k6io/k6/issues/1098, so I'll close this one in favor of the older one. Please follow it for updates instead.
