### ISSUE TITLE
window is not defined at _

### ISSUE THREAD

**Issue by kbariotis** [k6io/k6#1981]
I tried to bundle an npm module using [this guide](https://k6.io/docs/using-k6/modules/#bundling-node-modules) but instead of `lodash` I tried to load `xmlbuilder2`. It compiles succesfully but when I try to run the compiled file with k6, it says:

> ERRO[0102] ReferenceError: window is not defined at _ (file:///.../dist/script.js:2:45(5))

## Environment
- k6 version:
- OS and version: MacOS BigSur
- Docker version and image, if applicable:

## Expected Behavior
To run successfully

## Actual Behavior
Gives me the error above

## Steps to Reproduce the Problem

1. Follow this guide https://k6.io/docs/using-k6/modules/#bundling-node-modules
2. Instead of lodash, import `xmlbuilder2`

**Comment by na--** [comment]
As it very explicitly says in the warning in the [link you posted](https://k6.io/docs/using-k6/modules/#bundling-node-modules):
> k6 is not NodeJS, nor is it a browser. Packages that rely on APIs provided by NodeJS, for instance the `os` and `fs` modules, will not work in k6. **The same goes for browser-specific APIs like the `window` object.**

There might be some way to make `xmlbuilder2` work by playing with webpack options, if you can make it output something that doesn't depend on browser or NodeJS APIs :man_shrugging: In any case, the [k6 community forum](https://community.k6.io/) is probably a better place to search for help on the topic.
