### ISSUE TITLE
Persistent websocket connection errors after failed executions

### ISSUE THREAD

**Issue by bsjcho** [k6io/k6#1991]
## Environment

- k6 version: k6 v0.29.0 ((devel), go1.15.4, darwin/amd64)
- OS and version: Mac OS 11.2.3

## Expected Behavior
The ability to repeatedly run websocket load tests even when there are failures or abrupt terminations.

## Actual Behavior
After some number of test failures and abrupt terminations, attempts to connect to websocket servers fail and repeatedly return the following error:

```
ERRO[0002] GoError: websocket: bad handshake
running at github.com/loadimpact/k6/js/common.Bind.func1 (native)
default at file:///Users/.../basic_login_scenario.js:63:39(40)  executor=ramping-vus scenario=default source=stacktrace
```

Our websocket server logs show that when these errors begin appearing, there are no attempts to connect to the server. This leads us to believe that there is something on our mac client which is running k6 that is faulty and preventing the outbound connection request from happening.

We can only resolve this issue by restarting the OS.

## Steps to Reproduce the Problem
1. Run tests which initiate websocket connections.
2. Have test fail in some cases and/or abruptly end test execution (ctrl+c).
3. Rerunning the tests will, after some number of the above two events, yield repeated websocket handshake errors and no server-side visible attempts to reach the websocket server.

**Comment by bsjcho** [comment]
Updated title as it appears to be happening on Linux EC2 boxes as well.

![image](https://user-images.githubusercontent.com/1697001/116327655-23014080-a77c-11eb-9474-58fc5490d73d.png)

**Comment by imiric** [comment]
Hi @bsjcho, I suppose this ended up being a client-side / script issue and not a problem with k6? Can you confirm?

**Comment by bsjcho** [comment]
We didn’t realize we had Cloudflare in front of our load testing env. Some firewall rules were activating which was blocking traffic. We disabled those rules for that env and everything worked as intended!
