### ISSUE TITLE
WARN[0000] Request Failed ... socket: too many open files

### ISSUE THREAD

**Issue by adrianovieira** [k6io/k6#2006]
## Environment

- k6 version: `k6 v0.31.1 (2021-03-17T13:23:23+0000/e9d8349, go1.15.8, linux/amd64)`
- OS and version: Fedora-34
- Docker version and image, if applicable: NA

## Expected Behavior

Run without that <i>`WARN[0000] Request Failed`</i>

## Actual Behavior

```
WARN[0000] Request Failed                                error="Get \"http://localhost:3000\": dial tcp 127.0.0.1:3000: socket: too many open files"
```

## Steps to Reproduce the Problem

1. create a simple sample _deno_ `hello.ts` (or nodejs `hello.js`) server script, e.g.:

<details>

```typescript
// from https://deno.land/#getting-started
import { serve } from "https://deno.land/std@0.95.0/http/server.ts";
const s = serve({ port: 3000 });
console.log("http://localhost:3000/");
for await (const req of s) {
  req.respond({ body: "Hello World\n" });
}

```
OR nodejs script

```javascript
// from https://expressjs.com/en/starter/hello-world.html
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => {
  res.send('Hello World!')
})

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`)
})
```
</details>

2. `deno run --allow-net hello.ts` (or node `hello.js`)
3. create a k6 `script.k6.js`, e.g:

<details>

```javascript
// from https://k6.io/docs/getting-started/running-k6/#running-local-tests
import http from 'k6/http';
import { sleep } from 'k6';

const baseURL = __ENV.BASE_URL || `http://localhost:3000`;

export default function () {
  http.get(baseURL);
  sleep(1);
}
```
</details>

4. run the k6 `script.k6.js`: `k6 run --vus 1018 --duration 1s script.k6.js`
    If _vus_ is less than or equal 1017 k6 runs like a charm, but if it is 1018+ you get that error message multiplied by the number of _vus_ is greater than 1017, e.g: (1018 - 1017= 1x; 1020 - 1017= 3x). 

![image](https://user-images.githubusercontent.com/5561794/117179509-91ac5280-ada9-11eb-9d03-14a21ec52b70.png)

![image](https://user-images.githubusercontent.com/5561794/117182381-a76f4700-adac-11eb-8443-9619a0066e26.png)

**Comment by imiric** [comment]
Hi, this is not a k6 bug, but a Linux kernel limitation of the amount of open file descriptors per process, which includes open TCP connections. You can configure this with `ulimit -n`. See [our documentation about it](https://k6.io/docs/testing-guides/running-large-tests/#socket-too-many-open-files).
