### ISSUE TITLE
The repository 'https://dl.bintray.com/loadimpact/deb stable InRelease' is not signed

### ISSUE THREAD

**Issue by wmsken** [k6io/k6#2028]
Hi, wish you are having a good day.
I am using the VSTS pipeline to to my performance test by using K6, and before execute the k6 script, I need to install K6, and the following are the commands:

*sudo npm install -g k6-to-junit*
*wget -q -O - https://bintray.com/user/downloadSubjectPublicKey?username=bintray | sudo apt-key add -*
*echo "deb https://dl.bintray.com/loadimpact/deb stable main" | sudo tee -a /etc/apt/sources.list*
*sudo apt-get update*
*sudo snap install k6*

But there is exception when executing these commands, logs are as below:

*2021-05-18T07:23:52.4618813Z ##[section]Starting: Install k6 && k6-to-junit*

*2021-05-18T07:23:52.4836775Z ==============================================================================*

*2021-05-18T07:23:52.4837350Z Task         : Command line*

*2021-05-18T07:23:52.4837832Z Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows*

*2021-05-18T07:23:52.4838163Z Version      : 2.182.0*

*2021-05-18T07:23:52.4838537Z Author       : Microsoft Corporation*

*2021-05-18T07:23:52.4839215Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line*

*2021-05-18T07:23:52.4839618Z ==============================================================================*

*2021-05-18T07:23:52.7701327Z Generating script.*

*2021-05-18T07:23:52.7702594Z ========================== Starting Command Output ===========================*

*2021-05-18T07:23:52.7718586Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/d5b6f707-59ae-46f7-b76e-45cb97dfc4f8.sh*

*2021-05-18T07:24:05.5779149Z /usr/local/bin/k6-to-junit -> /usr/local/lib/node_modules/k6-to-junit/dist/command.js*

*2021-05-18T07:24:05.5851138Z + k6-to-junit@1.0.3*

*2021-05-18T07:24:05.5852136Z added 29 packages from 12 contributors in 4.842s*

*2021-05-18T07:24:05.8029033Z Warning: apt-key output should not be parsed (stdout is not a terminal)*

*2021-05-18T07:24:06.4925317Z OK*

*2021-05-18T07:24:06.5550388Z deb https://dl.bintray.com/loadimpact/deb stable main*

*2021-05-18T07:24:06.7496542Z Hit:1 http://azure.archive.ubuntu.com/ubuntu bionic InRelease*

*2021-05-18T07:24:06.7527030Z Get:2 http://azure.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]*

*2021-05-18T07:24:06.7528058Z Get:3 http://azure.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]*

*2021-05-18T07:24:06.7529075Z Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]*

*2021-05-18T07:24:06.7529941Z Hit:5 https://download.mono-project.com/repo/ubuntu stable-bionic InRelease*

*2021-05-18T07:24:06.9268223Z Hit:6 http://ppa.launchpad.net/apt-fast/stable/ubuntu bionic InRelease*

*2021-05-18T07:24:06.9737725Z Get:7 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease [4003 B]*

*2021-05-18T07:24:07.0196448Z Get:8 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2069 kB]*

*2021-05-18T07:24:07.0976223Z Hit:9 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease*

*2021-05-18T07:24:07.1022256Z Get:10 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main Translation-en [413 kB]*

*2021-05-18T07:24:07.1065652Z Get:11 http://azure.archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [344 kB]*

*2021-05-18T07:24:07.1114948Z Get:12 http://azure.archive.ubuntu.com/ubuntu bionic-updates/restricted Translation-en [46.8 kB]*

*2021-05-18T07:24:07.1131151Z Get:13 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1735 kB]*

*2021-05-18T07:24:07.1357437Z Get:14 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe Translation-en [369 kB]*

*2021-05-18T07:24:07.2010211Z Err:15 https://dl.bintray.com/loadimpact/deb stable InRelease*

*2021-05-18T07:24:07.2011152Z   403  Forbidden [IP: 52.32.150.221 443]*

*2021-05-18T07:24:07.2271084Z Hit:16 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic InRelease*

*2021-05-18T07:24:07.3591295Z Get:17 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [1725 kB]*

*2021-05-18T07:24:07.4823018Z Get:18 http://security.ubuntu.com/ubuntu bionic-security/main Translation-en [321 kB]*

*2021-05-18T07:24:07.4829153Z Get:19 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [323 kB]*

*2021-05-18T07:24:07.4891463Z Get:20 http://security.ubuntu.com/ubuntu bionic-security/restricted Translation-en [43.2 kB]*

*2021-05-18T07:24:07.4921217Z Get:21 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1125 kB]*

*2021-05-18T07:24:07.5115657Z Get:22 http://security.ubuntu.com/ubuntu bionic-security/universe Translation-en [253 kB]*

*2021-05-18T07:24:07.6912238Z Get:23 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages [186 kB]*

*2021-05-18T07:24:07.6916760Z Err:23 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages*

*2021-05-18T07:24:07.6917772Z   File has unexpected size (186036 != 185650). Mirror sync in progress? [IP: 40.118.250.56 443]*

*2021-05-18T07:24:07.6918236Z   Hashes of expected file:*

*2021-05-18T07:24:07.6919120Z    - Filesize:185650 [weak]*

*2021-05-18T07:24:07.6919989Z    - SHA512:3c4b7d3b74e5d1dbb64552a98ceb37afeb46f2df4ce12570dfaba9ef69e7478d7e83c135d16dd81adb834e76971eb7d880b8be7c94e11b4cff20243b61601e05*

*2021-05-18T07:24:07.6920759Z    - SHA256:436291009c4d1f23a9b0801a5a27d862a09f196d2f8b4570e88501df252ad66f*

*2021-05-18T07:24:07.6921461Z    - SHA1:ddc8d6031d1efea089674c486177fd4578296657 [weak]*

*2021-05-18T07:24:07.6921981Z    - MD5Sum:2cac2b69dd9614147477e4021b8a9a24 [weak]*

*2021-05-18T07:24:07.6922372Z   Release file created at: Sat, 15 May 2021 00:37:31 +0000*

*2021-05-18T07:24:12.3399306Z Reading package lists...*

*2021-05-18T07:24:12.3744507Z E: Failed to fetch https://dl.bintray.com/loadimpact/deb/dists/stable/InRelease  403  Forbidden [IP: 52.32.150.221 443]*

*2021-05-18T07:24:12.3746069Z E: The repository 'https://dl.bintray.com/loadimpact/deb stable InRelease' is not signed.*

*2021-05-18T07:24:12.4446391Z Reading package lists...*

*2021-05-18T07:24:12.6037460Z Building dependency tree...*

*2021-05-18T07:24:12.6050059Z Reading state information...*

*2021-05-18T07:24:12.7709290Z *

*2021-05-18T07:24:12.7710856Z No apt package "k6", but there is a snap with that name.*

*2021-05-18T07:24:12.7711833Z Try "snap install k6"*

*2021-05-18T07:24:12.7712412Z *

*2021-05-18T07:24:12.7759876Z E: Unable to locate package k6*

*2021-05-18T07:24:12.7843650Z ##[error]Bash exited with code '100'.*

I have no idea what the problem is because it is normal and I can install K6, execute K6 script before using the same commands.
Could you please help me if you know something about this.

Thanks,
Ken

**Comment by na--** [comment]
Bintray 

> I am using the VSTS pipeline to to my performance test by using K6, and before execute the k6 script, I need to install K6, and the following are the commands:

Where exactly did you see these commands? bintray shut down at the beginning of the month and I thought we'd fixed all of the installation instructions for k6 to the new [dl.k6.io](https://dl.k6.io/) repositories, but apparently we missed some? :confused: Please tell us where you found the bintray instructions so we can fix them.

Here are the details for the new repositories:
- https://k6.io/blog/sunsetting-bintray/
- https://k6.io/docs/getting-started/installation/

**Comment by wmsken** [comment]
Thank you na, these commands were written from last year and i don't know bintray has shut down at the beginning of the month and thought the root cause is any other, so I didn't refer to the new installation instructions for K6.
The new installation instructions for K6 already solves my problem.
Thanks again.
