### ISSUE TITLE
no breakline if there is any thresholds have faild when used handleSummary function

### ISSUE THREAD

**Issue by xyngfei** [k6io/k6#2032]
## Environment
- k6 version: k6 v0.32.0
- OS and version: 10.15.7 (19H512)

## Expected Behavior
Add the threshold 

```
export const options = {
    thresholds: {
        "http_req_duration": ["p(90)<100"],
    },
};

```

## Actual Behavior
Should hv break line, after that it will show the text "ERRO[0013] some thresholds have failed"

## Steps to Reproduce the Problem

![image](https://user-images.githubusercontent.com/17619539/118916020-c4854780-b960-11eb-9ca7-0257e42aad1f.png)

**Comment by na--** [comment]
@xyngfei, judging by that `Preparing the end-of-test summary...` log line I see, you seem to be using the `handleSummary()` function. So you can simply add a newline there and at the end. The default k6 summary does just that, see: 
https://github.com/k6io/k6/blob/e02986d0c42775d5dc3f9fe3b83cd4d572877d96/js/summary-wrapper.js#L66
