### ISSUE TITLE
Debug not works when use k6 with --no-usage-report parameter

### ISSUE THREAD

**Issue by brunowego** [k6io/k6#2042]
Is not showing the debug output when use with `--no-usage-report`.

## Environment

- k6 version: k6 v0.32.0 ((devel), go1.16.3, darwin/amd64)
- OS and version: macOS 11.3 (20E232)

## Steps to Reproduce the Problem

```Makefile
SHELL := /bin/sh

K6 ?= ulimit -n 4096 && GODEBUG=http2debug=2 k6
ENV ?= local

.DEFAULT_GOAL := stress

.PHONY: stress
stress:
	@$(K6) run \
		-e ENV=${ENV} \
		--no-usage-report \
		./test/stress/index.ts
```

**Comment by na--** [comment]
I don't have a mac, but just tested this on linux and `--no-usage-report` had no effect on `GODEBUG=http2debug=2`. And it really shouldn't have one, those parts of the code have nothing in common with each other... :confused: 

Are you sure this is the cause?

**Comment by MStoykov** [comment]
Also make certain you are actually hitting the SUT with http2 as otherwise, I would expect this won't print anything. 

On the other hand, the usage report endpoint is likely http2, so disabling it will remove even that debug output.

**Comment by brunowego** [comment]
Thanks a lot @na--  and @MStoykov. My SUT not are under HTTP2 protocol. Thanks again.
