### ISSUE TITLE
group() aren't set the group tag on request

### ISSUE THREAD

**Issue by radDunin** [k6io/k6#2069]
Hi,
I am using groups for different kind of request with different thresholds, once i use group tag as reference in threshold k6 doesn't seems to tagging requests inside group() and i didn't get threshold error.
```
import http from 'k6/http';
import { sleep, check, group } from 'k6';
import { textSummary } from 'https://jslib.k6.io/k6-summary/0.0.1/index.js';

export const options = {
  vus: 10,
  iterations: 100,
  thresholds: {
    'http_req_failed{group:getData}': ['rate<0.01'], // http errors should be less than 1%
    'http_req_failed{group:createData}': ['rate<0.01'], // http errors should be less than 1%
    // 99% of requests should be below 100ms and 50% within 34ms
    'http_req_duration{group:getData}': ['p(99)<100', 'p(50)<34'],
//i've expected that this will failed as it failed if i add additional tag or change it to 'method:POST'
    'http_req_duration{group:createData}': ['p(99)<1', 'p(50)<24']
  }
};
//two groups one for get and another for post
// one with get have own dynamic url - batch(request)
export default function() {
  group('getData', function() {
    const res = http.get('https://test.k6.io');
    sleep(0.1);
    check(res, {
      'is status 200': (r) => r.status === 200
      // 'body size is 1176 bytes': (r) => r.body.length == 1176
    });
  });
  group('createData', function() {
    const res = http.post('https://httpbin.test.k6.io/anything');
    check(res, {
      'is status 200': (r) => r.status === 200
    });
  });
}

export function handleSummary(data) {
  console.log('Preparing the end-of-test summary...');

  // Send the results to some remote server or trigger a hook
  return {
    stdout: textSummary(data, { indent: ' ', enableColors: true }), // Show the text summary to stdout...
    './summary.json': JSON.stringify(data) // and a JSON with all the details...
  };
}
```

in summary i didn't get any error but when i change tag in threshold at option from group:createData to method:POST it actually failed

What am i doing wrong if it is not a bug? in documentation i've read that group() should by default taging with group tag and name of current group request,checks etc.: https://k6.io/docs/using-k6/tags-and-groups#groups

"When a taggable resource: checks, requests, or custom metrics runs within a group, k6 will set the tag group with the current group name. Read more about it in Tags."

**Comment by MStoykov** [comment]
Hi @radDunin, 

This is because the documentation didn't have a good example. 

As I have now explained in this [PR's changes](https://github.com/k6io/docs/pull/342), the value of the tag `group` is the contamination of all group names that wrap the line emitting the metric, separated by a `::` ... so far so good, but there is also a default/root group called '' (empty string). So you just need to add '::' in front all the value like in:
```
  thresholds: {
    'http_req_failed{group:::getData}': ['rate<0.01'], // http errors should be less than 1%
    'http_req_failed{group:::createData}': ['rate<0.01'], // http errors should be less than 1%
    // 99% of requests should be below 100ms and 50% within 34ms
    'http_req_duration{group:::getData}': ['p(99)<100', 'p(50)<34'],
//i've expected that this will failed as it failed if i add additional tag or change it to 'method:POST'
    'http_req_duration{group:::createData}': ['p(99)<1', 'p(50)<24']
  }
```

**Comment by radDunin** [comment]
Thanks for the quick reply. Indeed it works with colons 🎉 I appreciate adding this to the documentation too :)  👍
