### ISSUE TITLE
Update babel&corejs fix the process for updating js libraries

### ISSUE THREAD

**Issue by MStoykov** [k6io/k6#981]
The current babel that we used is babel-standalone [6.26.0](https://github.com/babel/babel-standalone/releases/tag/release-6.26.0). (Fun thing the commit (0d465bf87752d084d76896b008ae0b1a5d172492) adds it is 2 months and 10 days younger than the code by ... the commit date :man_shrugging: ). Now 7.0+ has standalone built in. 
We should also update core-js (whatever version it currently is) , but given [the write up](https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md) by the core-js author maybe we can just go by with babel.

There are a couple of problems:
1. currently we have the source of both babel and core-js twice: once as files on disk and once as go.rice files ... this is probably not needed we need only the go.rice files and if we can write a script that automatically generates what is in the repo given it has network connection I am fine :). This will still mean that k6 will be completely buildable with only what is in the git repo and go, but if we want to regenerate the babel it will need network connection. 
2. Well documented what version from where we got for each of those dependencies, so next time we know (easily) from what we upgrade to what. Probably the script from 1 will do this well enough (I hope)
3. We should probably configure babel better. Supposedly we can remove some plugins add some and so on and so forth to get better ES6 compatibility. 
4. Way more and better tests for things that babel and corejs provide us ... currently this is what is stopping me form just start work on this. I have no idea if I will miss some babel plugin that is needed for something obvious  that we currently support and will break it ... 
5. Something that I have forgotten

**Comment by na--** [comment]
Some updates for this issue, though we might be better off closing it :man_shrugging: 

@MStoykov did something like this in a recent PR that dropped big parts of the currently bundled core.js: https://github.com/loadimpact/k6/pull/1772. The current consensus is that we'd completely drop core.js from k6 v0.31.0, so we're probably not going to merge it, but it's still a useful illustration how we don't need to commit the actual minified JS code in our repo.

It's unclear if we'll ever update babel now, whether with https://github.com/loadimpact/k6/pull/1663 or some other PR... If we ever do, we should just make sure to require something similar from the PR, so we drop `babel.min.js` from the repo as well.
